### ISSUE TITLE
Error: assets/icon.png is not or a valid PNG file.

### ISSUE THREAD

**Issue by YeCita** [JustYuuto/Grabber#5]
Error: assets/icon.png is not or a valid PNG file.
    at C:\Users\Gladius\AppData\Roaming\npm\node_modules\png-to-ico\lib\png.js:18:10

Node.js v18.11.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\Gladius\Downloads\Grabber-master\Grabber-master>

**Comment by JustYuuto** [comment]
Hello, the commit https://github.com/JustYuuto/Grabber/commit/782babdca65d4459f8c9a51c9f5c3f0cce4258ae might fix your issue. Thanks for using my grabber btw
